name: Build and Deploy dbt Docs

on:
  push:
    branches:
      - main

jobs:
  build-dbt-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT }}" > ~/.dbt/profiles.yml

      - name: Install dbt packages
        run: dbt deps
        working-directory: data_engineer/sql_examples

      - name: Generate dbt docs
        run: dbt docs generate
        working-directory: data_engineer/sql_examples

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data_engineer/sql_examples/target
